---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Setup profiler output directory
  file:
    path: /tmp/xdebug_profiles
    state: directory
    mode: 0777
  become: true
