---
- name: apt-get | apt-get update and ensure core packages are installed
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  tags: aptget
  become: true
  with_items: vlad_all_packages
