---

- name: Add the hostname aliases to the guest hosts file.
  lineinfile:
    dest: /etc/hosts
    regexp: "127.0.0.1 {{ webserver_hostname }}"
    insertafter: EOF
    line: "127.0.0.1 {{ webserver_hostname }}"
  become: true

- name: Add the hostname aliases to the guest hosts file.
  lineinfile:
    dest: /etc/hosts
    regexp: "127.0.0.1 {{ webserver_hostname_aliases|join(' ') }}"
    insertafter: EOF
    line: "127.0.0.1 {{ webserver_hostname_aliases|join(' ') }}"
  become: true
