---

# Drush commands
# ------------------------------------------------------------------------------

drush_install_commands:
  - { name: 'coder', version: ''}
  - { name: 'site_audit', version: ''}


# Drush make
# ------------------------------------------------------------------------------

# Vlad expects this file to be placed in a subdirectory called "make" within
# your vlad_aux directory.
# E.g. "vlad_example.make"
# Drush make will not be run if no file is specified.
drush_make_file: ''

# Options to pass to drush make command.
# E.g. "--prepare-install"
# See http://www.drushcommands.com/drush-7x/make/make for possible options.
drush_make_options: ''

# Run drush make every time the VM is provisioned.
# Setting to false will only run drush make if a make file has been specified
# and docroot is empty (checks for modules directory).
drush_make_force: false


# drushrc.php
# ------------------------------------------------------------------------------

drush_structure_tables: ['cache','cache_filter','cache_menu','cache_page','history','sessions','watchdog','cache_admin_menu','cache_block','cache_field','cache_form','cache_path','cache_token','cache_update','cache_views','cache_views_data','ctools_css_cache','ctools_object_cache','search_dataset','search_index','search_node_links','search_total']
